region:
  tacacs_sv_primary: "10.1.11.10"
  tacacs_sv_secondary: "10.1.11.8"
  tacacs_sv_tertiary: "10.1.11.9"

environments:
  syslog_server_primary: "10.1.10.30"

ntp_sv_1: "10.1.10.7"
ntp_sv_2: "10.1.10.6"
ntp_sv_3: "10.1.10.5"
ntp_sv_4: "10.1.10.4"
