---
- name: "01 - {{ inventory_hostname | upper }}: ENSURE OUTPUT DIRECTORY EXITS"
  file:
    path: "{{ output_dir }}/{{ inventory_hostname }}"
    state: "directory"

- name: "02 - {{ inventory_hostname | upper }}: GENERATE INTENDED CONFIG"
  template:
    src: "ntp.j2"
    dest: "{{ output_dir }}/{{ inventory_hostname }}/ntp.cfg"

- name: "03 - {{ inventory_hostname | upper }}: CHECK NTP CONFIG ON DEVICE"
  junos_config:
    update: "replace"
    src_format: "text"
    src: "{{ output_dir }}/{{ inventory_hostname }}/ntp.cfg"
  check_mode: true
  register: report

- name: "04 - GENERATE NTP REPORT"
  template:
    src: "ntp_report.j2"
    dest: "{{ output_dir }}/{{ inventory_hostname }}/20_ntp_report.md"