---
- name: "01: GET NON COMPLIANT SERVICES HOSTS"
  hosts: "localhost"
  connection: "local"
  gather_facts: no
  tasks:
    - include_role:
        name: "compliance_api"
      vars:
        cfg_section: "services"

- name: "02: PUSH CONFIGS TO FIX SERVICES COMPLIANCE"
  hosts: "services_non_compliant"
  connection: "netconf"
  gather_facts: no
  tasks:
    - include_role:
        name: "services"
