---
- name: "01: GET NON COMPLIANT SNMP HOSTS"
  hosts: "localhost"
  connection: "local"
  gather_facts: no
  tasks:
    - include_role:
        name: "compliance_api"
      vars:
        cfg_section: "snmp"

- name: "02: PUSH CONFIGS TO FIX SNMP COMPLIANCE"
  hosts: "snmp_non_compliant"
  connection: "netconf"
  gather_facts: no
  tasks:
    - include_role:
        name: "snmp"
