---
- name: "01: GET NON COMPLIANT SYSLOG HOSTS"
  hosts: "localhost"
  connection: "local"
  gather_facts: no
  tasks:
    - include_role:
        name: "compliance_api"
      vars:
        cfg_section: "syslog"

- name: "02: PUSH CONFIGS TO FIX SYSLOG COMPLIANCE"
  hosts: "syslog_non_compliant"
  connection: "netconf"
  gather_facts: no
  tasks:
    - include_role:
        name: "syslog"
