---
- name: "01 - {{ inventory_hostname | upper }}: ENSURE OUTPUT DIRECTORY EXITS"
  file:
    path: "{{ output_dir }}/{{ inventory_hostname }}"
    state: "directory"

- name: "02 - {{ inventory_hostname | upper }}: GENERATE INTENDED CONFIG"
  template:
    src: "services.j2"
    dest: "{{ output_dir }}/{{ inventory_hostname }}/services.cfg"

- name: "03 - {{ inventory_hostname | upper }}: CHECK SERVICES CONFIG ON DEVICE"
  junos_config:
    update: "replace"
    src_format: "text"
    src: "{{ output_dir }}/{{ inventory_hostname }}/services.cfg"
  check_mode: "true"
  register: "report"

- name: "04 - GENERATE SERVICES REPORT"
  template:
    src: "services_report.j2"
    dest: "{{ output_dir }}/{{ inventory_hostname }}/20_services_report.md"